export type { Budget } from './lib/bundle-budget.ts'
export type { OfficinaConfig } from './lib/config.ts'
export { defineConfig } from './lib/config.ts'
export type { IconSpec } from './lib/icon-specs.ts'
export type { VerifiedRoute } from './lib/routes.ts'
export type { CheckResult, SmokeCheck, SmokeContext } from './lib/smoke-production.ts'
